@url=http://localhost:5000/api/budgetperiods
@id=5dae27664330215bdc80776f
@did=5dae27664330215bdc80777f
@refreshToken=hEtvPjVk2xEE2Q5ODGBfZSfEzaAUABEaZ4jTk6RkKJhgk3wefAa3L66soMlvXkovuPivNWrAEClpeqIQXuBb0abLbc04NyZST5M2HDZSYTFxir0BRVuLkQtkWY4kIDdv
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYWUyNzY2NDMzMDIxNWJkYzgwNzc2ZiIsImlhdCI6MTU3OTI3MTI5OSwiZXhwIjoxNTc5Mjc0ODk5fQ.KgAv5SK0qbOkG7ePU_6Kfi3Zjif9oymWjht8xxJtfqs


### Get budget period by id
GET {{url}}/{{id}}
Accept: application/json
x-auth-token: {{accessToken}}
x-refresh-token: {{refreshToken}}

### Get list of budget periods
GET {{url}}?currentPage=0&resultsPerPage=10
Accept: application/json
x-auth-token: {{accessToken}}
x-refresh-token: {{refreshToken}}

### Get budgeted categories
GET {{url}}/{{id}}/budgetedcategories
Accept: application/json
x-auth-token: {{accessToken}}
x-refresh-token: {{refreshToken}}

### Get budget expenses
GET {{url}}/{{id}}/expenses?currentPage=0&resultsPerPage=10
Accept: application/json
x-auth-token: {{accessToken}}
x-refresh-token: {{refreshToken}}

### Get budget earnings
GET {{url}}/{{id}}/earnings?currentPage=0&resultsPerPage=10
Accept: application/json
x-auth-token: {{accessToken}}
x-refresh-token: {{refreshToken}}

### Register budget period
POST {{url}}
Content-Type: application/json
x-auth-token: {{accessToken}}
x-refresh-token: {{refreshToken}}

{
  "date": "January-2010"
}

### Activate budget period
PATCH {{url}}/activate/{{id}}
Content-Type: application/json
x-auth-token: {{accessToken}}
x-refresh-token: {{refreshToken}}

### Deactivate budget period
PATCH {{url}}/deactivate/{{did}}
Content-Type: application/json
x-auth-token: {{accessToken}}
x-refresh-token: {{refreshToken}}

### Delete a single budget period
DELETE {{url}}/{{id}}
Content-Type: application/json
x-auth-token: {{accessToken}}
x-refresh-token: {{refreshToken}}